language: java
jdk:
 - openjdk8
 - openjdk11
notifications:
  email:
    recipients:
      - jeldri2@towson.students.edu
    on_success: always # default: change
    on_failure: always # default: always
